### PR TITLE
UI: make header

### PR DESCRIPTION
**Pull request by harshbrahmxatriya**
Adding the sliding menu bar.
How to test:
Go to URL:https://deploy-preview-45--wehelpvip.netlify.app/
Part of UI - header

### CODE REVIEW

**Review by razbakov — CHANGES_REQUESTED** [review]
fonts in demo and figma are different. please fix

**Review by razbakov — CHANGES_REQUESTED** [review]
@harshbrahmxatriya in the popup font of links are not same as in design. please fix

**Comment by harshbrahmxatriya** [comment]
> @harshbrahmxatriya in the popup font of links are not same as in design. please fix
Is it? I zoomed it and to me it looks same
what say?

**Comment by razbakov** [comment]
- Seems everything works now. Merged

**Pull request merged**
